// Auth
export const FETCH_AUTH_TOKEN_REQUEST = "FETCH_AUTH_TOKEN_REQUEST";
export const FETCH_AUTH_TOKEN_SUCCCESS = "FETCH_AUTH_TOKEN_SUCCCESS";
export const FETCH_AUTH_TOKEN_ERROR = "FETCH_AUTH_TOKEN_ERROR";

// CMS Topics
export const FETCH_CMS_TOPICS_REQUEST = "FETCH_CMS_TOPICS_REQUEST";
export const FETCH_CMS_TOPICS_SUCCCESS = "FETCH_CMS_TOPICS_SUCCCESS";
export const FETCH_CMS_TOPICS_ERROR = "FETCH_CMS_TOPICS_ERROR";

// Topics manipulation
export const SET_RECOMENDED_TOPICS = "SET_RECOMENDED_TOPICS";
